print("-----------------------Student Profile-----------------------")
name=input("Enter your name:")
Age=int(input("Enter your age:"))
Student_id=int(input("Enter your student id:"))
branch=input("Enter your branch:")
college=input("Enter your college name:")
email=input("enter your email id:")
phone_no=input("Enter your phone number:")

print(f"Name:{name}")
print(f"Age:{Age}")
print(f"Student id:{Student_id}")
print(f"Branch:{branch}")
print(f"College name:{college}")
print(f"Email id:{email}")
print(f"Phone number:{phone_no}")